# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=25),
        ),
    ]
