# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170707_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='inventory_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
