# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170709_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderWidgets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='container',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='widgets',
        ),
        migrations.AlterField(
            model_name='widget',
            name='inventory_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='OrderDict',
        ),
        migrations.AddField(
            model_name='orderwidgets',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Order'),
        ),
        migrations.AddField(
            model_name='orderwidgets',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Widget'),
        ),
        migrations.AddField(
            model_name='order',
            name='widgets',
            field=models.ManyToManyField(through='core.OrderWidgets', to='core.Widget'),
        ),
    ]
