# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170709_1858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderWidgets',
            new_name='WidgetOrder',
        ),
    ]
