# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170709_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='inventory_number',
        ),
    ]
